apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: my-runner
spec:
  replicas: 1
  template:
    spec:
      repository: slawekzachcial/github-actions-k8s
      image: summerwind/actions-runner-dind
      dockerdWithinRunnerContainer: true
      labels:
        - my-runner
