name: Test Docker
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: [self-hosted, my-runner]
    container:
      image: docker:20.10.24-dind
    steps:
      - name: check out repository code
        uses: actions/checkout@v3
      - name: test docker inside container
        run: |
          docker ps

