name: Test Docker
on: [push]
jobs:
  test:
    runs-on: [self-hosted]
    container:
      image: docker:20.10.24
    steps:
      - name: check out repository code
        uses: actions/checkout@v3
      - name: test docker inside container
        run: |
          docker ps

